# Created by M. Maassenzio, 2020-09-06
#
# Configuration file for Frontend service.

server:
  workdir: /var/local/share/k8s-web
db:
  # The URI matches the <pod-name>-<seq>.<service-name>
  uri: "mongodb://mongo-node-0.mongo-cluster,mongo-node-1.mongo-cluster,mongo-node-2.mongo-cluster:27017/demo-db"
  collection: "entities"
