# A DB service, backed by a MongoDB Pod
# Using a "stateful" service (with a Persistent Volume)
#
# Reachable at URL:
# mongodb://mongo-node-0.mongo-cluster,mongo-node-1.mongo-cluster,mongo-node-2.mongo-cluster:27017/db_name

# Headless service for the StatefulSet.
apiVersion: v1
kind: Service
metadata:
  name: mongo-cluster

spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017

---
# The "stateful" Pod which
# uses a PVC to back its persistent data.
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: "mongo-node"
    labels:
      cluster: "mongodb-123-us-west-1"
      rel: "mongo-3.7"
spec:
  serviceName: mongo-cluster
  selector:
    matchLabels:
      # Must match the {{.spec.metadata.labels}} in the pods' {{.template}} below
      app: mongodb
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: "mongo:3.7"
          name: mongodb
          imagePullPolicy: "Always"
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
            - "--bind_ip"
            - 0.0.0.0
          ports:
          - containerPort: 27017
            protocol: TCP
          volumeMounts:
          - name: mongo-pvc
            mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      # Here the `name` MUST match the name in the `volumeMounts`
      name: mongo-pvc
    spec:
      resources:
        requests:
          storage: 20Mi
      accessModes:
      - ReadWriteOnce
