# Copyright (c) 2020 AlertAvert.com  All rights reserved.
# Created by M. Massenzio

apiVersion: batch/v1
kind: Job
metadata:
  name: replicas-job

spec:
  template:
    metadata:
      labels:
        app: replicas-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: replicas-job
          image: massenz/mongo-replicas:0.6.1
          imagePullPolicy: "Always"
