# Copyright Kapsules.io (c) 2018. All rights reserved.
#
# Pod running a number of utility containers for dev/testing.

apiVersion: v1
kind: Pod
metadata:
    name: utils
    labels:
      role: debug
      scope: dev
spec:
  containers:
    - image: massenz/dnsutils:2.0.0
      name: utils
      command: ["sleep"]
      args:
      - infinity
